name: Check API CI Tests
on:
  push:
    branches:
      - 'feature/*'
      - 'master'
      - 'test/*'
env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUB_ID: ${{ secrets.AZURE_SUB_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  SSH_KEY_USE1: ${{ secrets.SSH_KEY_USE1 }}
  SSH_KEY_USW2: ${{ secrets.SSH_KEY_USW2 }}
  VM_PASS: ${{ secrets.VM_PASS }}
  VM_USER: ${{ secrets.VM_USER }}
jobs:
  run-unit-tests:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: check python version
        run: python3 --version
      - name: check pip version
        run: pip3 --version
      - name: install tox
        run: pip3 install --upgrade tox
      - name: run tests
        run: make test
