name: Check API CI Tests
on: [push]
jobs:
    run-unit-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: python --version
        - run: pip install -r requirements.txt
        - run: python -m unittest discover tests
